/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPrimeiroAcessoRouteImport } from './routes/auth.primeiro-acesso'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAlunoRouteImport } from './routes/_authenticated/aluno'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTreinosRouteImport } from './routes/_authenticated/app.treinos'
import { Route as AuthenticatedAppProgramasRouteImport } from './routes/_authenticated/app.programas'
import { Route as AuthenticatedAppMarcaRouteImport } from './routes/_authenticated/app.marca'
import { Route as AuthenticatedAppGerarRouteImport } from './routes/_authenticated/app.gerar'
import { Route as AuthenticatedAppExerciciosRouteImport } from './routes/_authenticated/app.exercicios'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppArquivosRouteImport } from './routes/_authenticated/app.arquivos'
import { Route as AuthenticatedAppAlunosRouteImport } from './routes/_authenticated/app.alunos'
import { Route as AuthenticatedAppSessoesNovaRouteImport } from './routes/_authenticated/app.sessoes.nova'
import { Route as AuthenticatedAppSessoesIdRouteImport } from './routes/_authenticated/app.sessoes.$id'
import { Route as AuthenticatedAppExerciciosDuplicadosRouteImport } from './routes/_authenticated/app.exercicios.duplicados'
import { Route as AuthenticatedAlunoSessaoIdRouteImport } from './routes/_authenticated/aluno.sessao.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPrimeiroAcessoRoute = AuthPrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunoRoute = AuthenticatedAlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTreinosRoute = AuthenticatedAppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProgramasRoute =
  AuthenticatedAppProgramasRouteImport.update({
    id: '/programas',
    path: '/programas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMarcaRoute = AuthenticatedAppMarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGerarRoute = AuthenticatedAppGerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExerciciosRoute =
  AuthenticatedAppExerciciosRouteImport.update({
    id: '/exercicios',
    path: '/exercicios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppArquivosRoute =
  AuthenticatedAppArquivosRouteImport.update({
    id: '/arquivos',
    path: '/arquivos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlunosRoute = AuthenticatedAppAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSessoesNovaRoute =
  AuthenticatedAppSessoesNovaRouteImport.update({
    id: '/sessoes/nova',
    path: '/sessoes/nova',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessoesIdRoute =
  AuthenticatedAppSessoesIdRouteImport.update({
    id: '/sessoes/$id',
    path: '/sessoes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExerciciosDuplicadosRoute =
  AuthenticatedAppExerciciosDuplicadosRouteImport.update({
    id: '/duplicados',
    path: '/duplicados',
    getParentRoute: () => AuthenticatedAppExerciciosRoute,
  } as any)
const AuthenticatedAlunoSessaoIdRoute =
  AuthenticatedAlunoSessaoIdRouteImport.update({
    id: '/sessao/$id',
    path: '/sessao/$id',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/primeiro-acesso': typeof AuthPrimeiroAcessoRoute
  '/app/alunos': typeof AuthenticatedAppAlunosRoute
  '/app/arquivos': typeof AuthenticatedAppArquivosRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/exercicios': typeof AuthenticatedAppExerciciosRouteWithChildren
  '/app/gerar': typeof AuthenticatedAppGerarRoute
  '/app/marca': typeof AuthenticatedAppMarcaRoute
  '/app/programas': typeof AuthenticatedAppProgramasRoute
  '/app/treinos': typeof AuthenticatedAppTreinosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/aluno/sessao/$id': typeof AuthenticatedAlunoSessaoIdRoute
  '/app/exercicios/duplicados': typeof AuthenticatedAppExerciciosDuplicadosRoute
  '/app/sessoes/$id': typeof AuthenticatedAppSessoesIdRoute
  '/app/sessoes/nova': typeof AuthenticatedAppSessoesNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/auth/primeiro-acesso': typeof AuthPrimeiroAcessoRoute
  '/app/alunos': typeof AuthenticatedAppAlunosRoute
  '/app/arquivos': typeof AuthenticatedAppArquivosRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/exercicios': typeof AuthenticatedAppExerciciosRouteWithChildren
  '/app/gerar': typeof AuthenticatedAppGerarRoute
  '/app/marca': typeof AuthenticatedAppMarcaRoute
  '/app/programas': typeof AuthenticatedAppProgramasRoute
  '/app/treinos': typeof AuthenticatedAppTreinosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/aluno/sessao/$id': typeof AuthenticatedAlunoSessaoIdRoute
  '/app/exercicios/duplicados': typeof AuthenticatedAppExerciciosDuplicadosRoute
  '/app/sessoes/$id': typeof AuthenticatedAppSessoesIdRoute
  '/app/sessoes/nova': typeof AuthenticatedAppSessoesNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/primeiro-acesso': typeof AuthPrimeiroAcessoRoute
  '/_authenticated/app/alunos': typeof AuthenticatedAppAlunosRoute
  '/_authenticated/app/arquivos': typeof AuthenticatedAppArquivosRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/exercicios': typeof AuthenticatedAppExerciciosRouteWithChildren
  '/_authenticated/app/gerar': typeof AuthenticatedAppGerarRoute
  '/_authenticated/app/marca': typeof AuthenticatedAppMarcaRoute
  '/_authenticated/app/programas': typeof AuthenticatedAppProgramasRoute
  '/_authenticated/app/treinos': typeof AuthenticatedAppTreinosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/aluno/sessao/$id': typeof AuthenticatedAlunoSessaoIdRoute
  '/_authenticated/app/exercicios/duplicados': typeof AuthenticatedAppExerciciosDuplicadosRoute
  '/_authenticated/app/sessoes/$id': typeof AuthenticatedAppSessoesIdRoute
  '/_authenticated/app/sessoes/nova': typeof AuthenticatedAppSessoesNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aluno'
    | '/app'
    | '/auth/primeiro-acesso'
    | '/app/alunos'
    | '/app/arquivos'
    | '/app/configuracoes'
    | '/app/exercicios'
    | '/app/gerar'
    | '/app/marca'
    | '/app/programas'
    | '/app/treinos'
    | '/app/'
    | '/aluno/sessao/$id'
    | '/app/exercicios/duplicados'
    | '/app/sessoes/$id'
    | '/app/sessoes/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aluno'
    | '/auth/primeiro-acesso'
    | '/app/alunos'
    | '/app/arquivos'
    | '/app/configuracoes'
    | '/app/exercicios'
    | '/app/gerar'
    | '/app/marca'
    | '/app/programas'
    | '/app/treinos'
    | '/app'
    | '/aluno/sessao/$id'
    | '/app/exercicios/duplicados'
    | '/app/sessoes/$id'
    | '/app/sessoes/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aluno'
    | '/_authenticated/app'
    | '/auth/primeiro-acesso'
    | '/_authenticated/app/alunos'
    | '/_authenticated/app/arquivos'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/exercicios'
    | '/_authenticated/app/gerar'
    | '/_authenticated/app/marca'
    | '/_authenticated/app/programas'
    | '/_authenticated/app/treinos'
    | '/_authenticated/app/'
    | '/_authenticated/aluno/sessao/$id'
    | '/_authenticated/app/exercicios/duplicados'
    | '/_authenticated/app/sessoes/$id'
    | '/_authenticated/app/sessoes/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/primeiro-acesso': {
      id: '/auth/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/auth/primeiro-acesso'
      preLoaderRoute: typeof AuthPrimeiroAcessoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aluno': {
      id: '/_authenticated/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AuthenticatedAlunoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/treinos': {
      id: '/_authenticated/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AuthenticatedAppTreinosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/programas': {
      id: '/_authenticated/app/programas'
      path: '/programas'
      fullPath: '/app/programas'
      preLoaderRoute: typeof AuthenticatedAppProgramasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/marca': {
      id: '/_authenticated/app/marca'
      path: '/marca'
      fullPath: '/app/marca'
      preLoaderRoute: typeof AuthenticatedAppMarcaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gerar': {
      id: '/_authenticated/app/gerar'
      path: '/gerar'
      fullPath: '/app/gerar'
      preLoaderRoute: typeof AuthenticatedAppGerarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/exercicios': {
      id: '/_authenticated/app/exercicios'
      path: '/exercicios'
      fullPath: '/app/exercicios'
      preLoaderRoute: typeof AuthenticatedAppExerciciosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/arquivos': {
      id: '/_authenticated/app/arquivos'
      path: '/arquivos'
      fullPath: '/app/arquivos'
      preLoaderRoute: typeof AuthenticatedAppArquivosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alunos': {
      id: '/_authenticated/app/alunos'
      path: '/alunos'
      fullPath: '/app/alunos'
      preLoaderRoute: typeof AuthenticatedAppAlunosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sessoes/nova': {
      id: '/_authenticated/app/sessoes/nova'
      path: '/sessoes/nova'
      fullPath: '/app/sessoes/nova'
      preLoaderRoute: typeof AuthenticatedAppSessoesNovaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sessoes/$id': {
      id: '/_authenticated/app/sessoes/$id'
      path: '/sessoes/$id'
      fullPath: '/app/sessoes/$id'
      preLoaderRoute: typeof AuthenticatedAppSessoesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/exercicios/duplicados': {
      id: '/_authenticated/app/exercicios/duplicados'
      path: '/duplicados'
      fullPath: '/app/exercicios/duplicados'
      preLoaderRoute: typeof AuthenticatedAppExerciciosDuplicadosRouteImport
      parentRoute: typeof AuthenticatedAppExerciciosRoute
    }
    '/_authenticated/aluno/sessao/$id': {
      id: '/_authenticated/aluno/sessao/$id'
      path: '/sessao/$id'
      fullPath: '/aluno/sessao/$id'
      preLoaderRoute: typeof AuthenticatedAlunoSessaoIdRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
  }
}

interface AuthenticatedAlunoRouteChildren {
  AuthenticatedAlunoSessaoIdRoute: typeof AuthenticatedAlunoSessaoIdRoute
}

const AuthenticatedAlunoRouteChildren: AuthenticatedAlunoRouteChildren = {
  AuthenticatedAlunoSessaoIdRoute: AuthenticatedAlunoSessaoIdRoute,
}

const AuthenticatedAlunoRouteWithChildren =
  AuthenticatedAlunoRoute._addFileChildren(AuthenticatedAlunoRouteChildren)

interface AuthenticatedAppExerciciosRouteChildren {
  AuthenticatedAppExerciciosDuplicadosRoute: typeof AuthenticatedAppExerciciosDuplicadosRoute
}

const AuthenticatedAppExerciciosRouteChildren: AuthenticatedAppExerciciosRouteChildren =
  {
    AuthenticatedAppExerciciosDuplicadosRoute:
      AuthenticatedAppExerciciosDuplicadosRoute,
  }

const AuthenticatedAppExerciciosRouteWithChildren =
  AuthenticatedAppExerciciosRoute._addFileChildren(
    AuthenticatedAppExerciciosRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlunosRoute: typeof AuthenticatedAppAlunosRoute
  AuthenticatedAppArquivosRoute: typeof AuthenticatedAppArquivosRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppExerciciosRoute: typeof AuthenticatedAppExerciciosRouteWithChildren
  AuthenticatedAppGerarRoute: typeof AuthenticatedAppGerarRoute
  AuthenticatedAppMarcaRoute: typeof AuthenticatedAppMarcaRoute
  AuthenticatedAppProgramasRoute: typeof AuthenticatedAppProgramasRoute
  AuthenticatedAppTreinosRoute: typeof AuthenticatedAppTreinosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSessoesIdRoute: typeof AuthenticatedAppSessoesIdRoute
  AuthenticatedAppSessoesNovaRoute: typeof AuthenticatedAppSessoesNovaRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlunosRoute: AuthenticatedAppAlunosRoute,
  AuthenticatedAppArquivosRoute: AuthenticatedAppArquivosRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppExerciciosRoute: AuthenticatedAppExerciciosRouteWithChildren,
  AuthenticatedAppGerarRoute: AuthenticatedAppGerarRoute,
  AuthenticatedAppMarcaRoute: AuthenticatedAppMarcaRoute,
  AuthenticatedAppProgramasRoute: AuthenticatedAppProgramasRoute,
  AuthenticatedAppTreinosRoute: AuthenticatedAppTreinosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSessoesIdRoute: AuthenticatedAppSessoesIdRoute,
  AuthenticatedAppSessoesNovaRoute: AuthenticatedAppSessoesNovaRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlunoRoute: typeof AuthenticatedAlunoRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlunoRoute: AuthenticatedAlunoRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthPrimeiroAcessoRoute: typeof AuthPrimeiroAcessoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPrimeiroAcessoRoute: AuthPrimeiroAcessoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
