-- 1) Normaliza valores já existentes para a taxonomia oficial
UPDATE public.exercises SET equipamento = ARRAY['Kettlebell']
  WHERE equipamento @> ARRAY['kettlebell'] AND NOT equipamento @> ARRAY['Kettlebell'];
UPDATE public.exercises SET equipamento = ARRAY['Dumbbell']
  WHERE equipamento @> ARRAY['halteres'] AND NOT equipamento @> ARRAY['Dumbbell'];
UPDATE public.exercises SET equipamento = ARRAY['Barbell']
  WHERE equipamento @> ARRAY['barra'] AND NOT equipamento @> ARRAY['Barbell'];

-- 2) Backfill a partir do Excel (sobrescreve com a categoria oficial)
WITH src AS (
  SELECT * FROM (VALUES
    ('Kettlebell', $$alternate bridge press$$),
    ('Kettlebell', $$alternate row$$),
    ('Kettlebell', $$back squat$$),
    ('Kettlebell', $$black/dirty clean 2-1$$),
    ('Kettlebell', $$black/dirty snatch 2-1$$),
    ('Kettlebell', $$dead clean$$),
    ('Kettlebell', $$dead snatch$$),
    ('Kettlebell', $$deadlift$$),
    ('Kettlebell', $$elevação frontal$$),
    ('Kettlebell', $$elevação frontal isométrica$$),
    ('Kettlebell', $$figura$$),
    ('Kettlebell', $$figura clean$$),
    ('Kettlebell', $$figura clean com agachamento$$),
    ('Kettlebell', $$figura clean com lunge invertido$$),
    ('Kettlebell', $$goblet clean$$),
    ('Kettlebell', $$goblet clean to halo$$),
    ('Kettlebell', $$goblet cluster$$),
    ('Kettlebell', $$goblet lunge$$),
    ('Kettlebell', $$goblet lunge invertido$$),
    ('Kettlebell', $$goblet lunge vai-e-vem$$),
    ('Kettlebell', $$goblet press$$),
    ('Kettlebell', $$goblet snatch$$),
    ('Kettlebell', $$goblet squat$$),
    ('Kettlebell', $$goblet squat clean to halo$$),
    ('Kettlebell', $$goblet thruster$$),
    ('Kettlebell', $$gorilla row$$),
    ('Kettlebell', $$halo$$),
    ('Kettlebell', $$lenhador$$),
    ('Kettlebell', $$lenhador ajoelhado$$),
    ('Kettlebell', $$lenhador semi-ajoelhado$$),
    ('Kettlebell', $$one arm alternate high-pull$$),
    ('Kettlebell', $$one arm bottom-up clean$$),
    ('Kettlebell', $$one arm bottom-up long cycle$$),
    ('Kettlebell', $$one arm bottom-up press$$),
    ('Kettlebell', $$one arm bottom-up snatch$$),
    ('Kettlebell', $$one arm bridge press$$),
    ('Kettlebell', $$one arm clean$$),
    ('Kettlebell', $$one arm clean lateral$$),
    ('Kettlebell', $$one arm cluster$$),
    ('Kettlebell', $$one arm floor press$$),
    ('Kettlebell', $$one arm half-kneeling press$$),
    ('Kettlebell', $$one arm half-snatch$$),
    ('Kettlebell', $$one arm high-pull$$),
    ('Kettlebell', $$one arm jerk$$),
    ('Kettlebell', $$one arm kneeling press$$),
    ('Kettlebell', $$one arm long cycle$$),
    ('Kettlebell', $$one arm long cycle press$$),
    ('Kettlebell', $$one arm long cycle push press$$),
    ('Kettlebell', $$one arm press$$),
    ('Kettlebell', $$one arm push press$$),
    ('Kettlebell', $$one arm rack squat$$),
    ('Kettlebell', $$one arm row$$),
    ('Kettlebell', $$one arm snatch$$),
    ('Kettlebell', $$one arm snatch lateral$$),
    ('Kettlebell', $$one arm split jerk$$),
    ('Kettlebell', $$one arm swing$$),
    ('Kettlebell', $$one arm swing hand-to-hand$$),
    ('Kettlebell', $$one arm swing lateral$$),
    ('Kettlebell', $$one arm thruster$$),
    ('Kettlebell', $$pullover$$),
    ('Kettlebell', $$rl side walking swing$$),
    ('Kettlebell', $$rosca direta$$),
    ('Kettlebell', $$rosca unilateral$$),
    ('Kettlebell', $$rotational one arm clean$$),
    ('Kettlebell', $$rotational one arm dead clean$$),
    ('Kettlebell', $$rotational one arm dead snatch$$),
    ('Kettlebell', $$rotational one arm jerk$$),
    ('Kettlebell', $$rotational one arm press$$),
    ('Kettlebell', $$rotational one arm snatch$$),
    ('Kettlebell', $$seesaw bridge press$$),
    ('Kettlebell', $$side walking swing$$),
    ('Kettlebell', $$skull crusher$$),
    ('Kettlebell', $$slingshot diagonal$$),
    ('Kettlebell', $$slingshot lateral$$),
    ('Kettlebell', $$squat swing$$),
    ('Kettlebell', $$sumo deadlift com puxada alta$$),
    ('Kettlebell', $$swing 90º$$),
    ('Kettlebell', $$swing 180º$$),
    ('Kettlebell', $$swing base 4$$),
    ('Kettlebell', $$swing base 5$$),
    ('Kettlebell', $$swing vai-e-vem$$),
    ('Kettlebell', $$tríceps francês$$),
    ('Kettlebell', $$two arms bottom-up clean$$),
    ('Kettlebell', $$two arms bottom-up long cycle$$),
    ('Kettlebell', $$two arms bottom-up press$$),
    ('Kettlebell', $$two arms bottom-up snatch$$),
    ('Kettlebell', $$two arms bridge press$$),
    ('Kettlebell', $$two arms clean$$),
    ('Kettlebell', $$two arms half-snatch$$),
    ('Kettlebell', $$two arms hammer clean$$),
    ('Kettlebell', $$two arms hammer swing$$),
    ('Kettlebell', $$two arms high-pull$$),
    ('Kettlebell', $$two arms jerk$$),
    ('Kettlebell', $$two arms long cycle$$),
    ('Kettlebell', $$two arms long cycle press$$),
    ('Kettlebell', $$two arms long cycle push press$$),
    ('Kettlebell', $$two arms press$$),
    ('Kettlebell', $$two arms push press$$),
    ('Kettlebell', $$two arms row$$),
    ('Kettlebell', $$two arms snatch$$),
    ('Kettlebell', $$volta-ao-mundo$$),
    ('Kettlebell', $$walking swing$$),
    ('Kettlebell', $$one arm squat clean$$),
    ('Ginásticos', $$agachamento com salto$$),
    ('Ginásticos', $$agachamento lateral$$),
    ('Ginásticos', $$agachamentos com lunges$$),
    ('Ginásticos', $$agachamentos livres$$),
    ('Ginásticos', $$borboleta$$),
    ('Ginásticos', $$boxe sit-up$$),
    ('Ginásticos', $$burpees$$),
    ('Ginásticos', $$burpees com salto horizontal$$),
    ('Ginásticos', $$canoinha isométrica$$),
    ('Ginásticos', $$cócoras$$),
    ('Ginásticos', $$crunch$$),
    ('Ginásticos', $$crunch inferior$$),
    ('Ginásticos', $$crunch invertido$$),
    ('Ginásticos', $$crunch lateral$$),
    ('Ginásticos', $$elevação de pernas deitado$$),
    ('Ginásticos', $$elevação de pernas sentado$$),
    ('Ginásticos', $$elevação de quadris$$),
    ('Ginásticos', $$escaladores$$),
    ('Ginásticos', $$flexão bombardeiro$$),
    ('Ginásticos', $$flexão cobra$$),
    ('Ginásticos', $$flexão com rotação de tronco$$),
    ('Ginásticos', $$flexão de braços$$),
    ('Ginásticos', $$flexão hand release$$),
    ('Ginásticos', $$flutter kicks$$),
    ('Ginásticos', $$flutter kicks sentados$$),
    ('Ginásticos', $$groiner$$),
    ('Ginásticos', $$half v-up$$),
    ('Ginásticos', $$limpador de para-brisa$$),
    ('Ginásticos', $$lunge$$),
    ('Ginásticos', $$lunge estático$$),
    ('Ginásticos', $$lunge invertido$$),
    ('Ginásticos', $$lunge vai-e-vem$$),
    ('Ginásticos', $$minhoca$$),
    ('Ginásticos', $$nurpees$$),
    ('Ginásticos', $$polichinelos$$),
    ('Ginásticos', $$prancha lateral$$),
    ('Ginásticos', $$prancha reta$$),
    ('Ginásticos', $$prancha reta alta com toque$$),
    ('Ginásticos', $$push rocket$$),
    ('Ginásticos', $$remada renegada ginástica$$),
    ('Ginásticos', $$rotações russas$$),
    ('Ginásticos', $$sit-up$$),
    ('Ginásticos', $$superman$$),
    ('Ginásticos', $$superman superior$$),
    ('Ginásticos', $$tesoura$$),
    ('Ginásticos', $$tesoura sentado$$),
    ('Ginásticos', $$toque cruzado nos pés$$),
    ('Ginásticos', $$toque nos pés$$),
    ('Ginásticos', $$v-up$$),
    ('Ginásticos', $$v-up flutter kicks$$),
    ('Mobilidade', $$cachorro grande$$),
    ('Mobilidade', $$cachorro pequeno$$),
    ('Mobilidade', $$cobra$$),
    ('Mobilidade', $$cruz de ferro$$),
    ('Mobilidade', $$escorpião$$),
    ('Mobilidade', $$vaca-gato$$),
    ('Mobilidade', $$windmill$$),
    ('Mobilidade', $$posição do pombo$$),
    ('Mobilidade', $$alongamento de ísquios$$),
    ('Mobilidade', $$alongamento de quadríceps$$),
    ('Mobilidade', $$alongamento de panturrilhas$$),
    ('Mobilidade', $$rotação de tronco quadrupedal$$),
    ('Mobilidade', $$alongamento de adutores$$),
    ('Mobilidade', $$rock the bottom$$),
    ('Mobilidade', $$cócoras + rosca direta$$),
    ('Mobilidade', $$extensão de quadris semi-ajoelhada$$),
    ('Mobilidade', $$alongamento do sofá$$),
    ('Mobilidade', $$alongamento de glúteos$$),
    ('Mobilidade', $$alongamento de peitorais$$),
    ('Barbell', $$bb back squat$$),
    ('Barbell', $$bb deadlift$$),
    ('Barbell', $$bb front squat$$),
    ('Barbell', $$bb hang clean high pull$$),
    ('Barbell', $$bb hang muscle clean$$),
    ('Barbell', $$bb hang muscle snatch$$),
    ('Barbell', $$bb hang power clean$$),
    ('Barbell', $$bb hang power snatch$$),
    ('Barbell', $$bb hang snatch high pull$$),
    ('Barbell', $$bb hang squat clean$$),
    ('Barbell', $$bb hang squat snatch$$),
    ('Barbell', $$bb hang strict clean high pull$$),
    ('Barbell', $$bb hang strict snatch high pull$$),
    ('Barbell', $$bb overhead squat$$),
    ('Barbell', $$bb push jerk$$),
    ('Barbell', $$bb push press$$),
    ('Barbell', $$bb shoulder press$$),
    ('Barbell', $$bb snatch deadlift$$),
    ('Barbell', $$bb sumô deadlift$$),
    ('Barbell', $$bb sumo deadlift com puxada alta$$),
    ('Dumbbell', $$db elevação frontal$$),
    ('Dumbbell', $$db elevação lateral$$),
    ('Dumbbell', $$db one arm clean$$),
    ('Dumbbell', $$db one arm jerk$$),
    ('Dumbbell', $$db one arm long cycle$$),
    ('Dumbbell', $$db one arm long cycle press$$),
    ('Dumbbell', $$db one arm long cycle push press$$),
    ('Dumbbell', $$db one arm press$$),
    ('Dumbbell', $$db one arm push press$$),
    ('Dumbbell', $$db one arm snatch$$),
    ('Dumbbell', $$db remada$$),
    ('Dumbbell', $$db remada renegada$$),
    ('Dumbbell', $$db rosca direta$$),
    ('Dumbbell', $$db rosca hammer$$),
    ('Dumbbell', $$db seesaw press$$),
    ('Dumbbell', $$db squat$$),
    ('Dumbbell', $$db two arms clean$$),
    ('Dumbbell', $$db two arms jerk$$),
    ('Dumbbell', $$db two arms long cycle$$),
    ('Dumbbell', $$db two arms long cycle press$$),
    ('Dumbbell', $$db two arms long cycle push press$$),
    ('Dumbbell', $$db two arms press$$),
    ('Dumbbell', $$db two arms push press$$),
    ('Dumbbell', $$db two arms snatch$$),
    ('Objetos Alternativos', $$clubbell front squat$$),
    ('Objetos Alternativos', $$clubbell gamma cast$$),
    ('Objetos Alternativos', $$clubbell two arms barbarian squat$$),
    ('Objetos Alternativos', $$clubbell two arms chest press$$),
    ('Objetos Alternativos', $$clubbell two arms clean$$),
    ('Objetos Alternativos', $$clubbell two arms shoulder clean$$),
    ('Objetos Alternativos', $$clubbell two arms side swing$$),
    ('Objetos Alternativos', $$clubbell two arms squat clean$$),
    ('Objetos Alternativos', $$clubbell two arms swing$$),
    ('Objetos Alternativos', $$plate snatch$$),
    ('Objetos Alternativos', $$saltos de corda - su$$),
    ('Objetos Alternativos', $$saltos de corda du ??)$$)
  ) AS t(equipamento, nome_norm)
)
UPDATE public.exercises e
SET equipamento = ARRAY[src.equipamento]
FROM src
WHERE lower(regexp_replace(unaccent(e.nome_pt), '\s+', ' ', 'g')) = src.nome_norm
  AND NOT (COALESCE(e.equipamento, ARRAY[]::text[]) @> ARRAY[src.equipamento]);

-- 3) índice GIN para filtros por equipamento (coluna é text[])
CREATE INDEX IF NOT EXISTS exercises_equipamento_gin_idx ON public.exercises USING GIN (equipamento);